### ISSUE TITLE
`publish_pure_python` and `python-version` argument

### ISSUE THREAD

**Issue by nabobalis** [OpenAstronomy/github-actions-workflows#170]
Is there a reason it's called "python-version" and not either "python_version" or "default_python" which matches the tox workflows?

**Comment by ConorMacBride** [comment]
We should have used `-` in all the input names instead of `_` as that's what's typical for GitHub Actions. Unfortunately it's now inconsistent across all the inputs, but I don't think it's worth the effort to depreciate and migrate the input names.

The input for the build workflow specifies the actual version of Python to build for, while the input for the tox workflow specifies the default Python version to test with if the Python version is not specified in the tox environment name. That's why we don't use `default` in the build workflow name.

**Comment by nabobalis** [comment]
Thanks for the explanation. I agree that changing it would be too much effort at this point.
